blank_issues_enabled: false
contact_links:
  - name: ğŸ“– Documentation / æ–‡æ¡£
    url: https://github.com/huanshang141/notion-clipper/blob/main/README.md
    about: Please read the documentation before creating an issue / åœ¨åˆ›å»º Issue å‰è¯·å…ˆé˜…è¯»æ–‡æ¡£
